name: Release validation

on:
  push:
    branches: [ release-* ]
  pull_request:
    branches: [ release-* ]

jobs:        
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install Python and Flask
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install flask
        pip install requests
    
    - name: Build system
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Quality control
      run: |
        # Verifica se código atende ao padrão de qualidade
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run unitary tests
      run: |
        py -m unittest discover tests
        
  zip-files:
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: ./
          dest: den-bank.zip
      - uses: actions/upload-artifact@v1
        with:
          name: den-bank-v1
          path: ${{ github.workspace }}/den-bank.zip
        
        
