name: Feature validation

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:        
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install Python and Flask
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install requests
    
    - name: Build system
      run: |
        py server.py
        py client.py
    
    - name: Run unitary tests
      run: |
        py -m unittest discover tests

        
